name: pin_verification_code
description: Pin layout package
version: 0.0.01+1-dev.1
homepage: https://pub.dev/packages/pin_verification_code

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
